### PR TITLE
Add config option for iOS provisioning profile uuid

### PR DESCRIPTION
**Pull request by yomybaby**
With this PR, you don't have to select provisioning profile every time when you run `tifast send`.
You can select it when `tifast setup`.
😄

### CODE REVIEW

**Comment by ulizama** [comment]
I like the idea to be able to setup this so you don't have to send the args on send every time as you need to do now. But, don't you also need to set the `distribution_name` to avoid prompt?

**Comment by yomybaby** [comment]
You can set default iOS distribution cert using Titanium CLI.
Run `ti setup` command on terminal, enter 8 (iOS Settings), choose default cert.
After this, you don't need to select `distribution_name` every time when you build for Appstore and Ad-hoc. 😄

**Comment by yomybaby** [comment]
Actually, there are tons of build options. So how about add `ios_build_args` and `android_build_args` on `tifastlane.cfg`.
default values:
- `ios_build_args` : '-p ios -T dist-adhoc -O ./dist'
- `android_build_args` : '-p android -T dist-playstore -O ./dist'

With this option, you can add any options. 👍 
If you like `build_args` idea, I'll make an PR instead of this PR.

**Comment by ulizama** [comment]
Yes, I think that would be the best way to go.

**Comment by yomybaby** [comment]
Close this PR.
Please check #38 😄

**Pull request closed without merging**
