### PR TITLE
Updating to use Appcelerator CLI and add new Tools

### PR DESCRIPTION
**Pull request by DouglasHennrich**
I have update your module to use `appcelerator-cli` instead of `titanium-cli`.
I have reorder the CLI of tifastlane, add option to use `tifastlane` or just `tifast`.
Also add new tools. PEM, Snapshot and Pilot.

### CODE REVIEW

**Comment by DouglasHennrich** [comment]
someone is looking into this?

**Comment by ulizama** [comment]
Sorry, just saw the PR request.

This is really nice. I like your additions on locale, and I see that you are adding `pilot` as well.

I would only like to give the option to choose with CLI to use. I'm using `titanium-cli`.

**Comment by DouglasHennrich** [comment]
Hi! I guess we will need to make some updates on my pull request as well... I notice that when I upload my IPA, it be on "processing" forever and don't change =/
Maybe we should work on some logic to make the user choose which CLI he wants to use `ti` or `appc`

I'm glad that you like it =D
But I confess that still alot of thing to do

**Comment by ulizama** [comment]
Yeah the processing error is an issue with Fastlane directly, I haven't sent an app in a bit so haven't been able to test that, but if the issue stills remains we need to open a ticket on https://github.com/KrauseFx/deliver.

I'm thinking that we can default to `appc` and have it switch to `titanium` with something like this:

`tifast send --titanium`

**Comment by DouglasHennrich** [comment]
Good point... we should talk on a chat to fast communicate with each other ^^ 
But I have to say... my English isn't so good =X

**Comment by ulizama** [comment]
Are you on http://tislack.org/?

**Comment by DouglasHennrich** [comment]
Creating an account right now...

**Comment by DouglasHennrich** [comment]
still not receive the email from Slack...
Anyway... I already noticed some fixs we need to do if you merge this pull request

**Comment by ulizama** [comment]
I'm working in merging it with the changes I have. I'll update in a bit.

**Comment by DouglasHennrich** [comment]
Ok, Thanks for your time ^^
we will need a complete tutorial for all tools from `fastlane`

**Comment by ulizama** [comment]
I merged. Once you are on Slack we can comment on the other changes.

I appreciate your help, really good stuff ;)

**Comment by DouglasHennrich** [comment]
Thanks :D
I'm still waiting the confirm email to join on Slack

**Comment by DouglasHennrich** [comment]
Ok, I'm on Slack... `dhennrich` is my username

**Pull request merged**
